name: pysamsrf
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # Neuroimaging data I/O
  - nibabel>=3.2.0
  - h5py>=3.0.0  # For MATLAB v7.3 file support
  
  # Data manipulation and analysis
  - pandas>=1.3.0
  
  # Visualization
  - matplotlib>=3.5.0
  
  # Parallel processing
  - joblib>=1.1.0
  
  # Development and testing tools
  - pytest>=6.0.0
  - pytest-cov>=3.0.0
  - ipython
  - jupyter
  - jupyterlab
  
  # Code quality tools
  - black>=22.0.0
  - flake8>=4.0.0
  - mypy>=0.910
  
  # Optional but recommended dependencies
  - scikit-learn>=1.0.0
  - tqdm>=4.62.0
  
  # Install pysamsrf in development mode
  - pip:
    - -e .